services:
  redis:
    image: redis:6.2
    container_name: redis-zephyvid
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-zephyvid
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/videos:/usr/share/nginx/html/data/videos:ro
      - ./data/images:/usr/share/nginx/html/data/images:ro
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
